plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
Style/Documentation:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
Style/SymbolArray:
  EnforcedStyle: brackets
