services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      env_file: .env.development
  db:
    image: busybox
    volumes:
      - ./tmp/db:/app/db